@echo off
echo Fixing Tailwind CSS issue...

echo Step 1: Stopping any running processes...
taskkill /F /IM node.exe 2>nul

echo Step 2: Cleaning node_modules...
rd /s /q node_modules 2>nul
del package-lock.json 2>nul

echo Step 3: Installing specific Tailwind v3...
call npm install -D tailwindcss@3.3.3 postcss@8.4.31 autoprefixer@10.4.16

echo Step 4: Installing other dependencies...
call npm install

echo Step 5: Starting dev server...
call npm run dev